use SUCOS_VENDAS

SELECT
	A.EMBALAGEM,
	A.MAX_PRECO
FROM (SELECT 
			EMBALAGEM, 
			MAX([PREÇO DE LISTA]) AS MAX_PRECO 
		FROM [TABELA DE PRODUTOS] 
		GROUP BY EMBALAGEM) AS A
WHERE A.MAX_PRECO<=5

CREATE VIEW VW_EMBALAGEM AS
(SELECT 
	EMBALAGEM, 
	MAX([PREÇO DE LISTA]) AS MAX_PRECO 
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM)

SELECT * FROM VW_EMBALAGEM

CREATE VIEW TESTE_VIEW AS
(SELECT 
	EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO 
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM)


SELECT * FROM TESTE_VIEW