USE SUCOS_VENDAS

--LTRIM E RTRIM (TIRA OS ESPAÇOS EM BRANCO DO INICIO(ESQUERDA)/FINAL(DIREITA) DA STRING
SELECT LTRIM ('    OLA')
SELECT RTRIM ('OLA      ')
--CONCAT (CONCATENA DUAS STRINGS)
SELECT CONCAT('OLA,', ' TUDO BEM?')
SELECT 'OLA,' + ' TUDO BEM?'
--SUBSTRING (RETORNA PARTE DE UMA EXPRESSÃO DE CARACTERE, BINÁRIA, DE TEXTO OU DE IMAGEM)
SELECT LEFT('RUA AUGUSTA', 3)
SELECT RIGHT('RUA AUGUSTA', 7)
--LEN (RETORNA O NUMERO DE CARACTERES DA EXPRESSAO QUE TENHO NA CADEIA DE CARACTERES ESPECIFICADA, EXCLUINDO ESPAÇOS EM BRANCO À DIREITA)
SELECT LEN('RUA AUGUSTA')
--UPPER (TRANSFORMA A STRING DE MINISCULA PARA MAIUSCULA)
SELECT UPPER('rua augusta')
--LOWER (TRANSFORMA A STRING DE MAIUSCULA PARA MINUSCULA)
SELECT LOWER('RUA AUGUSTA')
--REPLACE (SUBSTITUI UM DETERMINADO STRING POR OUTRO)
SELECT REPLACE('abcdefghicde','cde','xxx')

--SUCOS VENDAS
SELECT
	NOME,
	[ENDERECO 1],
	BAIRRO,
	CIDADE,
	ESTADO,
	UPPER(CONCAT('RUA = ',[ENDERECO 1], ', BAIRRO = ', BAIRRO, ', CIDADE = ', CIDADE, ', ESTADO = ', ESTADO)) as ENDERECO_COMPLETO
FROM [TABELA DE CLIENTES]



--CURRENT_TIMESTAMP (RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E HORA DO COMPUTADOR QUE A INSTANCIA SQL ESTÁ EM EXECUÇÃO. NÃO CONTA FUSO HORÁRIO
SELECT CURRENT_TIMESTAMP
--GETDATE (RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E HORA DO COMPUTADOR QUE A INSTANCIA SQL ESTÁ EM EXECUÇÃO. NÃO CONTA FUSO HORÁRIO
SELECT GETDATE()
--GETUTCDATE (RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E HORA DO COMPUTADOR QUE A INSTANCIA SQL ESTÁ EM EXECUÇÃO. CONTEM O HORARIO UTC)
SELECT GETUTCDATE()
--DATENAME (RETORNA UMA CADEIA DE CARACTERES QUE REPRESENTA A DATEPART DA DATA ESPECIFICADA)
SELECT YEAR(GETDATE())
SELECT DATENAME(YEAR, GETDATE())
SELECT MONTH(GETDATE())
SELECT DATENAME(MONTH, GETDATE())
--DATEPART (RETORNA UM INTEIRO QUE REPRESENTA A DATEPART ESPECIFICADA DATA)
SELECT MONTH(GETDATE())
SELECT DATEPART(MONTH, GETDATE())
--DAY, MONTH, YEAR
SELECT DAY(GETDATE()), MONTH(GETDATE()), YEAR(GETDATE())
--DATEFROMPARTS (RETORNA UM VALOR DATA PARA O ANO, MES E DIA ESPECIFICADOS)
SELECT DATEFROMPARTS(2015,9,1)
SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1))
--DATEDIFF (RETORNA A DIFERENÇA INTEIRA ENTRE DATA OU HORA)
SELECT DATEDIFF(YEAR, DATEFROMPARTS(2015,9,1), GETDATE())
--DATEADD(RETORNA UM NOVO DATETIME COM O VALOR ADICIONADO AO INTERVALO)
SELECT DATEADD(DAY, 10, GETDATE())

--SUCOS VENDAS

SELECT * FROM [NOTAS FISCAIS]

SELECT CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA])) FROM [NOTAS FISCAIS]

SELECT * FROM [TABELA DE CLIENTES]
SELECT NOME,  DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) FROM [TABELA DE CLIENTES]

--CEILING (RETORNA O MENOR INTEIRO MAIOR OU IGUAL QUE A EXPRESSAO NUMERICA ESPECIFICADA)
SELECT CEILING(12.58)
--FLOOR (RETORNA O MAIOR INTEIRO MENOR OU IGUAL À EXPRESSAO NUMERICA ESPECIFIDADA)
SELECT FLOOR(12.58)
--RAND (RETORNA UM VALOR FLOAT ALEATORIO DE 0 A 1) OBS: PODEMOS MULTIPLICAR A FUNÇÃOPOR UM PARAMETRO
SELECT RAND()*10
--ROUND (ARREDONDA O NUMERO DE ACORDO COM A PRECISÃO ESCOLHIDA)
SELECT ROUND(10.534, 2)

--SUCOS VENDAS

SELECT
	YEAR(A.DATA),
	FLOOR(SUM(A.IMPOSTO*B.QUANTIDADE*B.PREÇO)) AS IMPOSTO_TOTAL
FROM [NOTAS FISCAIS] A
INNER JOIN [ITENS NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
WHERE YEAR(A.DATA)=2016
GROUP BY YEAR(A.DATA)

--CAST(SQL)/CONVERT(SQL SERVER) (REALIZAM CONVERSÕES DE DATAS)

SELECT CONVERT(VARCHAR, GETDATE(), 101)
SELECT CONVERT(VARCHAR, GETDATE(), 113)
SELECT CONVERT(DECIMAL(10,5), 193.57)


SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + CONVERT(VARCHAR, [PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]

--SUCOS VENDAS

SELECT
	CONCAT('O cliente ', A.NOME, ' faturou ', CONVERT(VARCHAR, CONVERT(DECIMAL(10,2), SUM(C.[QUANTIDADE]*C.[PREÇO]))), ' no ano de ', CONVERT(VARCHAR, YEAR(B.DATA))) AS SENTENCA
FROM [TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF=B.CPF
INNER JOIN [ITENS NOTAS FISCAIS] C
ON B.NUMERO=C.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY A.NOME, YEAR(DATA)








