use SUCOS_VENDAS

SELECT TOP 10 * FROM [TABELA DE CLIENTES] 

SELECT TOP 10 * FROM [TABELA DE PRODUTOS]

SELECT TOP 10 * FROM [TABELA DE VENDEDORES]

SELECT TOP 10 * FROM [NOTAS FISCAIS]

SELECT TOP 10 * FROM [ITENS NOTAS FISCAIS]



-- 1) Crie uma