USE SUCOS_VENDAS
--TABELA DE PRODUTOS
INSERT INTO [TABELA_DE_PRODUTOS]
(CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA )
VALUES
('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', 4.56)

INSERT INTO [TABELA_DE_PRODUTOS]
(CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA )
VALUES
('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01)

INSERT INTO [TABELA_DE_PRODUTOS]
(CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA )
VALUES
('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31)

select*
from TABELA_DE_PRODUTOS

--TABELA DE VENDEDORES
INSERT INTO [TABELA_DE_VENDEDORES]
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'José Geraldo da Fonseca', 0.1)

INSERT INTO [TABELA_DE_VENDEDORES]
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00235', 'Márcio Almeida Silva', 0.08)

INSERT INTO [TABELA_DE_VENDEDORES]
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236', 'Cláudia Morais', 0.08)

select*
from TABELA_DE_VENDEDORES
