USE SUCOS_VENDAS
--INSERINDO REGISTROS ERRADOS
INSERT INTO [TABELA_DE_PRODUTOS]
([CODIGO_DO_PRODUTO], [NOME_DO_PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO_DE_LISTA])
VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20)

INSERT INTO [TABELA_DE_PRODUTOS]
([CODIGO_DO_PRODUTO], [NOME_DO_PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO_DE_LISTA])
VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18)

select*
from TABELA_DE_PRODUTOS

--ATUALIZANDO OS REGISTROS

UPDATE [TABELA_DE_PRODUTOS] SET 
EMBALAGEM = 'Lata', PRECO_DE_LISTA = 2.46
WHERE CODIGO_DO_PRODUTO = '544931'

UPDATE [TABELA_DE_PRODUTOS] SET
EMBALAGEM = 'Garrafa'
WHERE CODIGO_DO_PRODUTO = '1078680'


UPDATE [TABELA_DE_VENDEDORES] SET
PERCENTUAL_COMISSAO = '0.11'
WHERE MATRICULA = '00238'

UPDATE [TABELA_DE_VENDEDORES] SET
NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233'

--EXCLUINDO DADOS
SELECT*
FROM TABELA_DE_PRODUTOS

DELETE FROM [TABELA_DE_PRODUTOS]
WHERE CODIGO_DO_PRODUTO = '1088126'

DELETE FROM [TABELA_DE_VENDEDORES]
WHERE MATRICULA = '00233'

--ALTERANDO COM CHAVE PRIMÁRIA

ALTER TABLE TABELA_DE_PRODUTOS
ALTER COLUMN CODIGO_DO_PRODUTO
VARCHAR(10) NOT NULL


ALTER TABLE TABELA_DE_PRODUTOS
ADD CONSTRAINT PK_PRODUTOS 
PRIMARY KEY CLUSTERED (CODIGO_DO_PRODUTO)

ALTER TABLE TABELA_DE_VENDEDORES
ALTER COLUMN MATRICULA
VARCHAR(20) NOT NULL

ALTER TABLE TABELA_DE_VENDEDORES
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED (MATRICULA)