USE SUCOS_VENDAS

ALTER TABLE TABELA_DE_CLIENTES
ALTER COLUMN CPF
VARCHAR(11) NOT NULL

ALTER TABLE TABELA_DE_CLIENTES
ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY CLUSTERED (CPF)

INSERT INTO TABELA_DE_CLIENTES
(CPF, NOME, [ENDERECO 1], [ENDERECO 2], BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES
('00300000001', 'João da Silva', 'Rua Projetada A número 10', '', 'Centro', 'Rio de Janeiro', 'RJ', '20000000', '1990-10-25', 27, 'M', 120000.50, 1000, 1)

SELECT*
FROM TABELA_DE_CLIENTES

ALTER TABLE TABELA_DE_VENDEDORES
ADD DATA_DE_ADMISSAO
DATE

ALTER TABLE TABELA_DE_VENDEDORES
ADD ESTADO_DE_FERIAS
BIT

UPDATE TABELA_DE_VENDEDORES SET
DATA_DE_ADMISSAO = '2014-08-15' 
WHERE MATRICULA = '00235'

UPDATE TABELA_DE_VENDEDORES SET
ESTADO_DE_FERIAS = 0
WHERE MATRICULA = '00235'

UPDATE TABELA_DE_VENDEDORES SET
DATA_DE_ADMISSAO = '2013-09-17' 
WHERE MATRICULA = '00236'

UPDATE TABELA_DE_VENDEDORES SET
ESTADO_DE_FERIAS = 1
WHERE MATRICULA = '00236'

UPDATE TABELA_DE_VENDEDORES SET
DATA_DE_ADMISSAO = '2017-03-18' 
WHERE MATRICULA = '00237'

UPDATE TABELA_DE_VENDEDORES SET
ESTADO_DE_FERIAS = 1
WHERE MATRICULA = '00237'

UPDATE TABELA_DE_VENDEDORES SET
DATA_DE_ADMISSAO = '2016-08-21' 
WHERE MATRICULA = '00238'

UPDATE TABELA_DE_VENDEDORES SET
ESTADO_DE_FERIAS = 0
WHERE MATRICULA = '00238'


SELECT*
FROM TABELA_DE_VENDEDORES