USE SUCOS_VENDAS
-- CONSULTAS NORMAIS
SELECT *  FROM [ITENS NOTAS FISCAIS] WHERE [QUANTIDADE] > 60 AND [PREÇO] <= 3
SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'LATA'
SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-9-11'

-- DATAS

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995
SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 11
SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 25


--NOT, IN, LIKE, AND, OR
SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR = 'Manga' OR TAMANHO = '700 ML'

SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR = 'MANGA' AND TAMANHO = '700 ML'

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT (SABOR = 'MANGA' AND TAMANHO = '700 ML')

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT (SABOR = 'MANGA' OR TAMANHO = '700 ML')

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT (SABOR = 'MANGA') AND TAMANHO = '700 ML'

SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('MANGA', 'LARANJA') -- SERIA IGUAL A SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR= 'MANGA' OR SABOR = 'LARANJA'

SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('MANGA', 'LARANJA') AND [PRE�O DE LISTA] BETWEEN 10 AND 13 -- SERIA IGUAL A SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('MANGA', 'LARANJA') AND [PRE�O DE LISTA] >= 10 AND [PRE�O DE LISTA] <= 13

SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR NOT IN ('MANGA', 'LARANJA')

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE 'L%'

SELECT * FROM [TABELA DE CLIENTES] WHERE [NOME] LIKE '%MATTOS'

--DISTINCT

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE SABOR = 'LARANJA'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]

SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES] WHERE CIDADE= 'Rio de Janeiro'

--TOP

SELECT TOP 4 * FROM [TABELA DE CLIENTES]

SELECT DISTINCT TOP 3 EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT TOP 10 * FROM [NOTAS FISCAIS] WHERE DATA = '2017-01-01'

--ORDER BY

SELECT * FROM [TABELA DE CLIENTES] ORDER BY NOME

SELECT EMBALAGEM, [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM, [NOME DO PRODUTO]

SELECT MAX([PRE�O DE LISTA]) FROM [TABELA DE PRODUTOS]

SELECT EMBALAGEM, [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]
ORDER BY EMBALAGEM DESC, [NOME DO PRODUTO] ASC


SELECT * FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
ORDER BY QUANTIDADE DESC

--GROUP BY

SELECT ESTADO, ROUND(SUM([LIMITE DE CREDITO]), 2)
FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, ROUND(AVG([LIMITE DE CREDITO]), 2)
FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT 
	EMBALAGEM, 
	MAX([PRE�O DE LISTA]) AS PRECO_MAXIMO,  
	MIN([PRE�O DE LISTA]) AS PRECO_MINIMO, 
	AVG([PRE�O DE LISTA]) AS MEDIA_PRECOS,
	COUNT (*) AS QUANTIDADE_DE_EMBALAGENS
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT 
	BAIRRO, 
	ESTADO, 
	SUM([LIMITE DE CREDITO]) AS LIMITE_CREDITO_TOTAL_POR_BAIRRO
FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP'
GROUP BY BAIRRO, ESTADO

SELECT
	COUNT(QUANTIDADE) AS TOTAL_ITENS_VENDA_COM_MAIOR_QUANTIDADE
FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035' AND QUANTIDADE = 99

SELECT 
	YEAR(DATA), 
	COUNT(*) 
FROM [NOTAS FISCAIS] 
GROUP BY YEAR(DATA)
ORDER BY YEAR(DATA) ASC

--HAVING (UTILIZADA PARA FAZER UM FILTRO SOBRE UM GROUP BY)

SELECT 
	BAIRRO, 
	ESTADO, 
	SUM([LIMITE DE CREDITO]) AS LIMITE_CREDITO_TOTAL_POR_BAIRRO
FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP'
GROUP BY BAIRRO, ESTADO
HAVING SUM([LIMITE DE CREDITO])>=140000

SELECT ESTADO, SUM([LIMITE DE CREDITO]) 
FROM [TABELA DE CLIENTES]
GROUP BY ESTADO
HAVING SUM([LIMITE DE CREDITO])>=850000

SELECT 
	EMBALAGEM, 
	MAX([PRE�O DE LISTA]) AS PRECO_MAXIMO,  
	MIN([PRE�O DE LISTA]) AS PRECO_MINIMO, 
	AVG([PRE�O DE LISTA]) AS MEDIA_PRECOS,
	SUM([PRE�O DE LISTA]) AS SOMA_PRECOS,
	COUNT (*) AS QUANTIDADE_DE_EMBALAGENS
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM
HAVING SUM([PRE�O DE LISTA])>80 AND MAX([PRE�O DE LISTA])>10

SELECT
	CPF,
	COUNT(CPF) AS QUANTIDADE_DE_COMPRAS
FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = '2016'
GROUP BY CPF
HAVING COUNT(CPF)>=2000

--CASE 

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 
	[NOME DO PRODUTO],
	CASE WHEN [PRE�O DE LISTA] >= 12 THEN 'PRODUTO CARO'
		 WHEN [PRE�O DE LISTA] >= 7 AND [PRE�O DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		 ELSE 'PRODUTO BARATO'
		 END AS QUALIFICACAO
FROM [TABELA DE PRODUTOS]

SELECT 
	[NOME DO PRODUTO],
	CASE WHEN [PRE�O DE LISTA] >= 12 THEN 'PRODUTO CARO'
		 WHEN [PRE�O DE LISTA] >= 7 AND [PRE�O DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		 ELSE 'PRODUTO BARATO'
	END AS QUALIFICACAO,
	AVG([PRE�O DE LISTA]) AS PRECO_DE_LISTA_MEDIO
FROM [TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
	CASE WHEN [PRE�O DE LISTA] >= 12 THEN 'PRODUTO CARO'
		 WHEN [PRE�O DE LISTA] >= 7 AND [PRE�O DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		 ELSE 'PRODUTO BARATO'
		 END 


SELECT
	NOME,
	CASE WHEN YEAR([DATA DE NASCIMENTO])<1990 THEN 'ADULTOS'
		 WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVENS'
		 ELSE 'CRIAN�AS'
	END AS QUALIFICACAO
FROM [TABELA DE CLIENTES]
