USE SUCOS_VENDAS

--INNER JOIN

SELECT *
FROM [TABELA DE VENDEDORES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.MATRICULA = B. MATRICULA


SELECT 
	A.MATRICULA, 
	A.NOME,
	COUNT(*) AS QUANTIDADE
FROM [TABELA DE VENDEDORES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, A.NOME
ORDER BY COUNT(*) DESC

SELECT 
	A.MATRICULA, 
	A.NOME,
	YEAR(B.DATA),
	COUNT(*) AS QUANTIDADE
FROM [TABELA DE VENDEDORES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, A.NOME, YEAR(B.DATA)
ORDER BY A.MATRICULA, YEAR(B.DATA)

SELECT
	ROUND(SUM(B.QUANTIDADE*B.PREÇO), 2) AS FATURAMENTO,
	YEAR(A.DATA)
FROM [NOTAS FISCAIS] A
INNER JOIN [ITENS NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
GROUP BY YEAR(A.DATA)
ORDER BY YEAR(A.DATA)

SELECT * FROM [TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF

SELECT 
	A.NOME,
	COUNT(*) AS NUMERO_DE_OCORRENCIAS
FROM [TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.NOME

SELECT * FROM [TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF

SELECT 
	A.NOME,
	COUNT(*) AS NUMERO_DE_OCORRENCIAS
FROM [TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.NOME

--LEFT JOIN E RIGHT JOIN

SELECT 
	A.NOME,
	COUNT(*) AS NUMERO_DE_OCORRENCIAS
FROM [TABELA DE CLIENTES] A
LEFT JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.NOME

SELECT 
	A.NOME,
	A.CPF,
	COUNT(*) AS NUMERO_DE_OCORRENCIAS
FROM [TABELA DE CLIENTES] A
LEFT JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
GROUP BY A.NOME, A.CPF

SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '95939180787'

--FULL JOIN AND CROSS JOIN

SELECT
	A.BAIRRO AS BAIRRO_VENDEDORES,
	B.BAIRRO AS BAIRRO_CLIENTES
FROM [TABELA DE VENDEDORES] A
INNER JOIN [TABELA DE CLIENTES] B
ON A.BAIRRO = B.BAIRRO

SELECT
	A.BAIRRO AS BAIRRO_VENDEDORES,
	B.BAIRRO AS BAIRRO_CLIENTES
FROM [TABELA DE VENDEDORES] A
LEFT JOIN [TABELA DE CLIENTES] B
ON A.BAIRRO = B.BAIRRO

SELECT
	A.BAIRRO AS BAIRRO_VENDEDORES,
	B.BAIRRO AS BAIRRO_CLIENTES
FROM [TABELA DE VENDEDORES] A
RIGHT JOIN [TABELA DE CLIENTES] B
ON A.BAIRRO = B.BAIRRO

SELECT
	A.BAIRRO AS BAIRRO_VENDEDORES,
	B.BAIRRO AS BAIRRO_CLIENTES
FROM [TABELA DE VENDEDORES] A
FULL JOIN [TABELA DE CLIENTES] B
ON A.BAIRRO = B.BAIRRO


SELECT
	A.BAIRRO AS BAIRRO_VENDEDORES,
	B.BAIRRO AS BAIRRO_CLIENTES
FROM [TABELA DE VENDEDORES] A
CROSS JOIN [TABELA DE CLIENTES] B





